### PR TITLE
Adding async storage strategy to export

### PR DESCRIPTION
**Pull request by cognitivedesire**

### CODE REVIEW

**Comment by cognitivedesire** [comment]
Hello can you please add this update and create a new npm build, I am stuck right now

**Comment by angelnikolov** [comment]
@cognitivedesire Sure thing, give me an hour :)

**Comment by cognitivedesire** [comment]
Also can I use PCacheable on Observable returning method? And can you explain what is async on ICacheConfig

**Comment by angelnikolov** [comment]
`async` adds additional `delay()` to `Cacheable` only. It's done so projects using angularjs can still run without the requirement of having additional $scope.$apply and etc.. You can't use `PCacheable` on Observable returning method, only `Cacheable`..

**Comment by cognitivedesire** [comment]
Thanks for clarifying, please do let me know when it's out on npm

**Comment by angelnikolov** [comment]
@cognitivedesire 1.4.1 is published.

**Comment by cognitivedesire** [comment]
Thank you so much

**Comment by cognitivedesire** [comment]
@angelnikolov I am not able to use DomStorageStrategy, I am setting the global config in app.component's constructor

**Comment by angelnikolov** [comment]
Well, the best thing to do now would be to create a stackblitz or codesandbox with that issue reproducing. Not sure how I can help otherwise :)

**Comment by cognitivedesire** [comment]
I'll do that but generally where do you suggest to keep global config

**Pull request merged**
